#!/usr/bin/bash
# -*- coding: utf-8 -*-

VARNAME="$(cat /tmp.usr)"

mkdir /etc/sddm.conf.d
cp -av /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf.d

sed -i 's/Numlock=none/Numlock=on/' /etc/sddm.conf.d/default.conf
sed -i "s/User=/User=$VARNAME/" /etc/sddm.conf.d/default.conf
sed -i 's/Session=/Session=xfce/' /etc/sddm.conf.d/default.conf

cp -av /usr/share/sddm/faces/.face.icon /usr/share/sddm/faces/"$VARNAME".face.icon
cp -av /usr/share/sddm/faces/root.face.icon /root/.face.icon
cp -av /usr/share/sddm/faces/.face.icon /home/"$VARNAME"/.face.icon

setfacl -m u:sddm:x /usr/share/sddm/faces/
setfacl -m u:sddm:x /root/
setfacl -m u:sddm:x /home/"$VARNAME"/
setfacl -m u:sddm:r /usr/share/sddm/faces/.face.icon
setfacl -m u:sddm:r /usr/share/sddm/faces/root.face.icon
setfacl -m u:sddm:r /usr/share/sddm/faces/"$VARNAME".face.icon
setfacl -m u:sddm:r /root/.face.icon
setfacl -m u:sddm:r /home/"$VARNAME"/.face.icon

sed -i '/^HOOKS=.*/s/fsck)/plymouth)/' /etc/mkinitcpio.conf
sed -i '/^HOOKS=.*/s/consolefont //g' /etc/mkinitcpio.conf
mkinitcpio -P

sed -i 's/quiet/quiet splash rd.udev.log_level=3 vt.global_cursor_default=0/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

xfconf-query -c xfce4-session -np '/shutdown/ShowSuspend' -t 'bool' -s 'false'
xfconf-query -c xfce4-session -np '/shutdown/ShowHibernate' -t 'bool' -s 'false'
xfconf-query -c xfce4-session -np '/shutdown/ShowSwitchUser' -t 'bool' -s 'false'
xfconf-query -c xfce4-session -np '/shutdown/ShowHybridSleep' -t 'bool' -s 'false'

mkdir /etc/xdg/xfce4/kiosk
echo -e "[xfce4-session]\nSaveSession=NONE" > /etc/xdg/xfce4/kiosk/kioskrc
