#!/usr/bin/bash
# -*- coding: utf-8 -*-

sed -i 's/#\[multilib\]/\[multilib\]/' /etc/pacman.conf
sed -i '/\[multilib\]/a Include = \/etc\/pacman.d\/mirrorlist' /etc/pacman.conf

pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
pacman-key --lsign-key 3056513887B78AEB
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' --noconfirm

echo -e "[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

pacman -Syyuu --noconfirm

pacman -Sy pamac-aur visual-studio-code-bin --noconfirm

sed -i 's/#EnableAUR/EnableAUR/' /etc/pamac.conf
