#!/usr/bin/bash
# -*- coding: utf-8 -*-

mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

pacman -Sy reflector --noconfirm
reflector --verbose --latest 5 --age 6 --number 10 --sort rate --save /etc/pacman.d/mirrorlist

pacstrap /mnt base base-devel linux-firmware linux-zen linux-zen-headers mc sudo networkmanager

genfstab -U /mnt >> /mnt/etc/fstab

# cp -av ./install-2 /mnt
cp -av ../install /mnt

arch-chroot /mnt
sh /install/install-2
