#!/usr/bin/bash
# -*- coding: utf-8 -*-

HOST_NAME=archlinux

pacman -Syyuu --noconfirm

pacman -S reflector --noconfirm

reflector --verbose --latest 10 --age 6 --number 10 --sort rate --save /etc/pacman.d/mirrorlist

pacman -S ppp netctl ntp dhcpcd dhclient samba git sshfs net-tools --noconfirm
pacman -S xorg xorg-apps xorg-drivers xorg-xinit xorg-xprop --noconfirm
pacman -S xfce4 sddm gvfs networkmanager network-manager-applet --noconfirm
pacman -S ttf-liberation ttf-dejavu ccache sccache dosfstools plymouth --noconfirm

pacman -S grub efibootmgr os-prober bash-completion --noconfirm

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable ntpd systemd-networkd systemd-resolved dhcpcd NetworkManager sshd sddm

sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

loadkeys ru
setfont cyr-sun16

sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen

echo -e "#LANG=en_US.UTF-8\nLANG=ru_RU.UTF-8" > /etc/locale.conf
echo -e "KEYMAP=ru\nFONT=cyr-sun16" > /etc/vconsole.conf

locale-gen

echo "Enter your time zone:"
ln -sf /usr/share/zoneinfo/"$(tzselect)" /etc/localtime

echo "${HOST_NAME}" > /etc/hostname

echo -e "127.0.0.1   localhost\n::1         localhost\n127.0.1.1   ${HOST_NAME}.localdomain  ${HOST_NAME}" > /etc/hosts

echo "Enter a new username:"
read -r VARNAME

useradd -m -g users -G wheel -s /bin/bash "$VARNAME"

echo "Set passwords for 'root':"
passwd

echo "Set passwords for '$VARNAME':"
passwd "$VARNAME"

export TEST_VAR="$VARNAME"
